version: '3.8'

services:
  for_test_sqlalchemy:
    image: postgres:alpine
    container_name: test_sqlalchemy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_sqlalchemy_db

volumes:
  postgres_data:
